resources:
- repo: self
  fetchDepth: '1'
pool:
  vmImage: ubuntu-latest
trigger:
- staging
variables:
  BuildConfiguration: 'Release'
  DockerImageName: 'sedayuone/landrope'
steps:
- task: CmdLine@1
  displayName: 'Lock image version in deployment.yaml'
  inputs:
    filename: /bin/bash
    arguments: '-c "awk ''{gsub(\"LAND_IMAGE\", \"asia.gcr.io/$(DockerImageName):$(Build.BuildId)\", $0); print}'' deployment-dev.yaml > $(build.artifactstagingdirectory)/deployment-dev.yaml"'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
- task: Docker@2
  displayName: 'Login to Container Registry'
  inputs:
    command: login
    containerRegistry: 'gcr-sedayuone'
- task: Docker@2
  displayName: 'Build and push image'
  inputs:
    Dockerfile: 'Dockerfile'
    command: buildAndPush
    repository: '$(DockerImageName)'