name: $(Build.SourceBranchName).landrope-api.$(Rev:r)
resources:
  - repo: self
    fetchDepth: 1
pool:
  vmImage: ubuntu-latest
trigger:
  - master
  - staging
  - dev
variables:
  BuildConfiguration: "Release"
  DockerImageName: "sedayuone/landrope/$(Build.SourceBranchName)/landrope_api"
steps:
  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact"
    inputs:
      PathtoPublish: "$(build.artifactstagingdirectory)"
  - task: Docker@2
    displayName: "Login to Container Registry"
    inputs:
      command: login
      containerRegistry: "gar-sedayuone"
  - task: Docker@2
    displayName: "Build and push image"
    inputs:
      Dockerfile: "Dockerfile"
      command: buildAndPush
      repository: "$(DockerImageName)"
