"""30 Agustus 2024 17:10 - Table Pelepasan

Revision ID: 39c3339208f4
Revises: 0cc9e3089319
Create Date: 2024-08-30 18:01:06.139793

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '39c3339208f4'
down_revision = '0cc9e3089319'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pelepasan_header',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('nomor_pelepasan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tanggal_pelepasan', sa.Date(), nullable=True),
    sa.Column('project_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('desa_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('nama_pemilik', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alamat_pemilik', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nomor_ktp_pemilik', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nomor_telepon_pemilik', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ptsk_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('jenis_surat_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('alashak', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tanda_tangan', sa.Boolean(), nullable=True),
    sa.Column('tanda_tangan_saksi', sa.Boolean(), nullable=True),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_lock', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['desa_id'], ['desa.id'], ),
    sa.ForeignKeyConstraint(['jenis_surat_id'], ['jenis_surat.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['ptsk_id'], ['ptsk.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pelepasan_header_id'), 'pelepasan_header', ['id'], unique=False)
    op.create_table('pelepasan_bidang',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('bidang_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('pelepasan_header_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['bidang_id'], ['bidang.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['pelepasan_header_id'], ['pelepasan_header.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pelepasan_bidang_id'), 'pelepasan_bidang', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pelepasan_bidang_id'), table_name='pelepasan_bidang')
    op.drop_table('pelepasan_bidang')
    op.drop_index(op.f('ix_pelepasan_header_id'), table_name='pelepasan_header')
    op.drop_table('pelepasan_header')
    # ### end Alembic commands ###
