"""_m_099

Revision ID: 01ead61ce4e6
Revises: 933c9fbffd6e
Create Date: 2024-04-01 16:57:06.249645

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '01ead61ce4e6'
down_revision = '933c9fbffd6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_bayar',
    sa.Column('termin_bayar_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('invoice_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['termin_bayar_id'], ['termin_bayar.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_bayar_id'), 'invoice_bayar', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_bayar_id'), table_name='invoice_bayar')
    op.drop_table('invoice_bayar')
    # ### end Alembic commands ###
