"""file type

Revision ID: 02a3f76fc717
Revises: e8551f7b8f0e
Create Date: 2023-07-24 17:32:41.117433

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '02a3f76fc717'
down_revision = 'e8551f7b8f0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bundle_dt', 'file_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bundle_dt', sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
