"""spk

Revision ID: 03ea40cf68ef
Revises: 
Create Date: 2023-09-26 20:04:14.861686

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '03ea40cf68ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spk', 'nilai',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spk', 'nilai',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###
