"""_m_0026

Revision ID: 05a7e39e21cb
Revises: 1d270152532b
Create Date: 2023-11-27 10:24:14.672899

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '05a7e39e21cb'
down_revision = '1d270152532b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spk', sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spk', 'remark')
    # ### end Alembic commands ###
