"""checklist kelengkapan dokumen

Revision ID: 0d80868ad2ca
Revises: 21d3d95d4563
Create Date: 2023-08-18 10:17:38.782043

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '0d80868ad2ca'
down_revision = '21d3d95d4563'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
