"""_m_107

Revision ID: 11f542f86407
Revises: 481279eedb55
Create Date: 2024-04-22 10:40:32.929210

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '11f542f86407'
down_revision = '481279eedb55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('termin_bayar', sa.Column('pay_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('termin_bayar', 'pay_to')
    # ### end Alembic commands ###
