"""8_history_data_tanda_terima_dt

Revision ID: 170fe766782c
Revises: 6d48f77f9ba7
Create Date: 2023-07-10 10:51:54.690209

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '170fe766782c'
down_revision = '6d48f77f9ba7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tanda_terima_notaris_dt', sa.Column('history_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tanda_terima_notaris_dt', 'history_data')
    # ### end Alembic commands ###
