"""8_Remove Geom Fields on PTSK

Revision ID: 1880355f6484
Revises: ba11d3bf7fe3
Create Date: 2023-04-27 14:24:06.104374

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '1880355f6484'
down_revision = 'ba11d3bf7fe3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ptsk_geom', table_name='ptsk')
    op.drop_column('ptsk', 'geom')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ptsk', sa.Column('geom', geoalchemy2.types.Geometry(from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True))
    op.create_index('idx_ptsk_geom', 'ptsk', ['geom'], unique=False)
    # ### end Alembic commands ###
