"""_12 JULI 2024__add beban pembeli on inv detail

Revision ID: 1e25b43047ff
Revises: 746b7bce4df5
Create Date: 2024-07-12 17:06:31.289966

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '1e25b43047ff'
down_revision = '746b7bce4df5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_detail', sa.Column('beban_pembeli', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_detail', 'beban_pembeli')
    # ### end Alembic commands ###
