"""10_is_disabled_request_petlok

Revision ID: 1eed5d18c385
Revises: ea5a5595ee0a
Create Date: 2023-07-10 17:11:49.687184

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '1eed5d18c385'
down_revision = 'ea5a5595ee0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_peta_lokasi', sa.Column('is_disabled', sa.Boolean(), nullable=True))
    op.alter_column('request_peta_lokasi', 'dibuat_oleh',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('request_peta_lokasi', 'diperiksa_oleh',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('request_peta_lokasi', 'diterima_oleh',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_peta_lokasi', 'diterima_oleh',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('request_peta_lokasi', 'diperiksa_oleh',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('request_peta_lokasi', 'dibuat_oleh',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('request_peta_lokasi', 'is_disabled')
    # ### end Alembic commands ###
