"""38 planing tanda terima notaris

Revision ID: 2109b9666bb1
Revises: 75350ac8c310
Create Date: 2023-06-21 11:08:02.443131

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '2109b9666bb1'
down_revision = '75350ac8c310'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kjb_dt', sa.Column('luas_surat_ttn', sa.Numeric(), nullable=False))
    op.add_column('kjb_dt', sa.Column('planing_ttn_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'kjb_dt', 'planing', ['planing_ttn_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kjb_dt', type_='foreignkey')
    op.drop_column('kjb_dt', 'planing_ttn_id')
    op.drop_column('kjb_dt', 'luas_surat_ttn')
    # ### end Alembic commands ###
