"""4_add field status on gps table2

Revision ID: 21112aeac6d3
Revises: acfc9b52ab33
Create Date: 2023-04-17 15:02:00.243603

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '21112aeac6d3'
down_revision = 'acfc9b52ab33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gps', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gps', 'status')
    # ### end Alembic commands ###
