"""getall

Revision ID: 265553125d67
Revises: 88e87704344d
Create Date: 2023-08-15 11:55:18.527398

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '265553125d67'
down_revision = '88e87704344d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bidang_overlap', 'bidang', ['parent_bidang_intersect_id'], ['id'])
    op.create_foreign_key(None, 'bidang_overlap', 'bidang', ['parent_bidang_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bidang_overlap', type_='foreignkey')
    op.drop_constraint(None, 'bidang_overlap', type_='foreignkey')
    # ### end Alembic commands ###
