"""tanggal rencana transaksi

Revision ID: 27fe68641f2c
Revises: d73f303de8c0
Create Date: 2023-10-11 11:48:41.957904

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '27fe68641f2c'
down_revision = 'd73f303de8c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('name_unique', 'kategori', type_='unique')
    op.add_column('termin', sa.Column('tanggal_rencana_transaksi', sa.Date(), nullable=True))
    op.add_column('termin', sa.Column('notaris_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('termin', 'notaris_id')
    op.drop_column('termin', 'tanggal_rencana_transaksi')
    op.create_unique_constraint('name_unique', 'kategori', ['name'])
    # ### end Alembic commands ###
