"""jenis_lahan rincik  nullable true

Revision ID: 28ce13afbc38
Revises: b943437e6ae2
Create Date: 2023-04-13 11:08:11.766537

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '28ce13afbc38'
down_revision = 'b943437e6ae2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
