"""spk code

Revision ID: 29a26dec0043
Revises: 8a3d792dd3e1
Create Date: 2023-09-20 10:47:57.479371

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '29a26dec0043'
down_revision = '8a3d792dd3e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bidang_komponen_biaya', sa.Column('is_void', sa.Boolean(), nullable=True))
    op.add_column('bidang_komponen_biaya', sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('spk', sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spk', 'code')
    op.drop_column('bidang_komponen_biaya', 'remark')
    op.drop_column('bidang_komponen_biaya', 'is_void')
    # ### end Alembic commands ###
