"""11_remove Code on SKPT

Revision ID: 2e0349a782f3
Revises: d5c93f6d41d1
Create Date: 2023-05-02 11:07:20.387576

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e0349a782f3'
down_revision = 'd5c93f6d41d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mappingplaningptsk', sa.Column('skpt_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.drop_constraint('mappingplaningptsk_ptsk_id_fkey', 'mappingplaningptsk', type_='foreignkey')
    op.create_foreign_key(None, 'mappingplaningptsk', 'skpt', ['skpt_id'], ['id'])
    op.drop_column('mappingplaningptsk', 'ptsk_id')
    op.drop_column('skpt', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skpt', sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('mappingplaningptsk', sa.Column('ptsk_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mappingplaningptsk', type_='foreignkey')
    op.create_foreign_key('mappingplaningptsk_ptsk_id_fkey', 'mappingplaningptsk', 'ptsk', ['ptsk_id'], ['id'])
    op.drop_column('mappingplaningptsk', 'skpt_id')
    # ### end Alembic commands ###
