"""33 Tanda Terima Notaris Dt

Revision ID: 2ea11c244084
Revises: 9f0c08b05972
Create Date: 2023-06-13 16:21:16.619355

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '2ea11c244084'
down_revision = '9f0c08b05972'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tanda_terima_notaris_dt',
    sa.Column('tanggal_tanda_terima', sa.DateTime(), nullable=True),
    sa.Column('dokumen_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('meta_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tanggal_terima_dokumen', sa.DateTime(), nullable=True),
    sa.Column('tanda_terima_notaris_hd_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dokumen_id'], ['dokumen.id'], ),
    sa.ForeignKeyConstraint(['tanda_terima_notaris_hd_id'], ['tanda_terima_notaris_hd.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tanda_terima_notaris_dt_id'), 'tanda_terima_notaris_dt', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tanda_terima_notaris_dt_id'), table_name='tanda_terima_notaris_dt')
    op.drop_table('tanda_terima_notaris_dt')
    # ### end Alembic commands ###
