"""__takeout is ptsl on kjb dt

Revision ID: 3261edabb028
Revises: 2e7f3c8a436b
Create Date: 2024-06-03 11:33:13.767769

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '3261edabb028'
down_revision = '2e7f3c8a436b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kjb_dt', 'is_ptsl')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kjb_dt', sa.Column('is_ptsl', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
