"""draft

Revision ID: 39f45a1718aa
Revises: e46c87fd67ae
Create Date: 2023-08-11 10:51:48.684549

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '39f45a1718aa'
down_revision = 'e46c87fd67ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'draft_detail', 'draft', ['draft_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'draft_detail', type_='foreignkey')
    # ### end Alembic commands ###
