"""25_is keyword

Revision ID: 3a44db1b383c
Revises: 1fb400b5edd3
Create Date: 2023-05-31 11:52:00.344175

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '3a44db1b383c'
down_revision = '1fb400b5edd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dokumen', sa.Column('is_keyword', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dokumen', 'is_keyword')
    # ### end Alembic commands ###
