"""komponen biaya dan invoice

Revision ID: 3fffc042a619
Revises: 3571a3d0cfcf
Create Date: 2023-09-19 14:10:17.596375

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '3fffc042a619'
down_revision = '3571a3d0cfcf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
