"""12_id bidang lama

Revision ID: 40ead00fe1d9
Revises: f86160c35123
Create Date: 2023-07-11 17:58:32.607357

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '40ead00fe1d9'
down_revision = 'f86160c35123'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bidang', sa.Column('id_bidang_lama', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bidang', 'id_bidang_lama')
    # ### end Alembic commands ###
