"""27 AGUSTUS 2024 16:50 - Kategori Id on Closing

Revision ID: 4254c6bccf17
Revises: 6bdbe3ee6f41
Create Date: 2024-08-27 16:53:52.438948

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '4254c6bccf17'
down_revision = '6bdbe3ee6f41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bidang_closing', sa.Column('kategori_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'bidang_closing', 'kategori', ['kategori_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bidang_closing', type_='foreignkey')
    op.drop_column('bidang_closing', 'kategori_id')
    # ### end Alembic commands ###
