"""_m_0056

Revision ID: 445c09c20530
Revises: 84ff66b465a8
Create Date: 2024-01-16 13:58:30.906887

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '445c09c20530'
down_revision = '84ff66b465a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('import_temp_kjb_detail')
    # op.drop_table('import_temp_request_petlok')
    # op.drop_table('import_temp_ttn')
    # op.drop_table('import_temp_kjb_termin')
    # op.drop_table('import_temp_kjb_harga')
    # op.drop_table('import_temp_kjb')
    # op.drop_table('import_temp_kjb_beban')
    op.add_column('kjb_hd', sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('kjb_hd', 'kategori_penjual',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('kjb_hd', 'luas_kjb',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('kjb_hd', 'manager_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('kjb_hd', 'sales_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('kjb_hd', 'ada_utj',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('kjb_hd', 'utj_amount',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('kjb_hd', 'satuan_bayar',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('kjb_hd', 'satuan_harga',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kjb_hd', 'satuan_harga',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('kjb_hd', 'satuan_bayar',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('kjb_hd', 'utj_amount',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('kjb_hd', 'ada_utj',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('kjb_hd', 'sales_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('kjb_hd', 'manager_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('kjb_hd', 'luas_kjb',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('kjb_hd', 'kategori_penjual',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('kjb_hd', 'file_path')
    op.create_table('import_temp_kjb_beban',
    sa.Column('kjb_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('beban_biaya', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('beban_pembeli', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.create_table('import_temp_kjb',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('kjb_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('tanggal_kjb', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('kategori_penjual', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('group_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('desa', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('luas_kjb', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('manager', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sales', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mediator', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('telepon_mediator', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('remark', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('penjual', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bank', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nomor_rekening', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('utj_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('import_temp_kjb_harga',
    sa.Column('kjb_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('jenis_alashak', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('harga_akta', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('harga_transaksi', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('import_temp_kjb_termin',
    sa.Column('kjb_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('jenis_alashak', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('jenis_bayar', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nilai', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('import_temp_ttn',
    sa.Column('alashak', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('project', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('desa', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pemilik', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tanggal_tanda_terima', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('nomor_tanda_terima', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notaris', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('luas_surat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status_peta_lokasi', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    op.create_table('import_temp_request_petlok',
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tanggal', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('alashak', sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.create_table('import_temp_kjb_detail',
    sa.Column('kjb_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('jenis_alashak', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('jenis_surat', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('alashak', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('posisi_bidang', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('harga_akta', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('harga_transaksi', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('luas_surat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('penjual', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bundle_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('project', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('desa', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('group_name', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
