"""20_GPS add SKPT Id

Revision ID: 448b95dec1cf
Revises: e0d520c136ce
Create Date: 2023-05-05 11:40:57.086991

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '448b95dec1cf'
down_revision = 'e0d520c136ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gps', sa.Column('skpt_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'gps', 'skpt', ['skpt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gps', type_='foreignkey')
    op.drop_column('gps', 'skpt_id')
    # ### end Alembic commands ###
