"""_m_0037

Revision ID: 48b67dd847f3
Revises: b77e7dbb0fc8
Create Date: 2023-12-05 16:25:15.616121

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '48b67dd847f3'
down_revision = 'b77e7dbb0fc8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hasil_peta_lokasi_history',
    sa.Column('meta_data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trans_worker_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('trans_at', sa.DateTime(), nullable=False),
    sa.Column('hasil_peta_lokasi_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['hasil_peta_lokasi_id'], ['hasil_peta_lokasi.id'], ),
    sa.ForeignKeyConstraint(['trans_worker_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hasil_peta_lokasi_history_id'), 'hasil_peta_lokasi_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hasil_peta_lokasi_history_id'), table_name='hasil_peta_lokasi_history')
    op.drop_table('hasil_peta_lokasi_history')
    # ### end Alembic commands ###
