"""_add harga ptsl

Revision ID: 4be48d30bb05
Revises: e0654760339f
Create Date: 2024-05-15 20:22:44.692597

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '4be48d30bb05'
down_revision = 'e0654760339f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bidang', sa.Column('harga_ptsl', sa.Numeric(), nullable=True))
    op.add_column('bidangorigin', sa.Column('harga_ptsl', sa.Numeric(), nullable=True))
    op.add_column('kjb_dt', sa.Column('harga_ptsl', sa.Numeric(), nullable=True))
    op.add_column('kjb_harga', sa.Column('harga_ptsl', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kjb_harga', 'harga_ptsl')
    op.drop_column('kjb_dt', 'harga_ptsl')
    op.drop_column('bidangorigin', 'harga_ptsl')
    op.drop_column('bidang', 'harga_ptsl')
    # ### end Alembic commands ###
