"""__add txn id field on workflow

Revision ID: 4cebf85d08b7
Revises: 06636379d435
Create Date: 2024-07-04 18:03:51.544479

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '4cebf85d08b7'
down_revision = '06636379d435'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('txn_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow', 'txn_id')
    # ### end Alembic commands ###
