"""_m_0012

Revision ID: 4cfa40d3894e
Revises: 7a2820909447
Create Date: 2023-10-23 10:27:23.162567

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '4cfa40d3894e'
down_revision = '7a2820909447'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('giro', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('payment', sa.Column('void_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('payment', sa.Column('void_at', sa.Date(), nullable=True))
    op.add_column('payment_detail', sa.Column('void_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('payment_detail', sa.Column('void_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_detail', 'void_at')
    op.drop_column('payment_detail', 'void_reason')
    op.drop_column('payment', 'void_at')
    op.drop_column('payment', 'void_reason')
    op.alter_column('giro', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
