"""_m_0019

Revision ID: 51e9ec40c478
Revises: dc6e7ffaef93
Create Date: 2023-11-09 16:27:09.613936

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '51e9ec40c478'
down_revision = 'dc6e7ffaef93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('void_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('invoice', sa.Column('void_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('invoice', sa.Column('void_at', sa.Date(), nullable=True))
    op.create_foreign_key(None, 'invoice', 'worker', ['void_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice', type_='foreignkey')
    op.drop_column('invoice', 'void_at')
    op.drop_column('invoice', 'void_reason')
    op.drop_column('invoice', 'void_by_id')
    # ### end Alembic commands ###
