"""_m_0061

Revision ID: 54f5eddba4d1
Revises: f4ffedeed413
Create Date: 2024-01-26 16:46:53.967742

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '54f5eddba4d1'
down_revision = 'f4ffedeed413'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bundle_dt', sa.Column('multiple_count', sa.Integer(), nullable=True))
    op.add_column('kjb_dt', sa.Column('jumlah_waris', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kjb_dt', 'jumlah_waris')
    op.drop_column('bundle_dt', 'multiple_count')
    # ### end Alembic commands ###
