"""___termin rfp payment init

Revision ID: 55ba211b7ef5
Revises: e06fe62f199a
Create Date: 2024-05-03 16:20:55.221478

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '55ba211b7ef5'
down_revision = 'e06fe62f199a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('termin_rfp_payment',
    sa.Column('termin_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('rfp_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('payment_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['termin_id'], ['termin.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_termin_rfp_payment_id'), 'termin_rfp_payment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_termin_rfp_payment_id'), table_name='termin_rfp_payment')
    op.drop_table('termin_rfp_payment')
    # ### end Alembic commands ###
