"""bidang

Revision ID: 55c779f4a8db
Revises: 
Create Date: 2023-08-07 16:25:17.479203

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '55c779f4a8db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_category_dokumen_id', table_name='category_dokumen')
    op.drop_table('category_dokumen')
    op.add_column('bidang', sa.Column('bundle_hd_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'bidang', 'bundle_hd', ['bundle_hd_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bidang', type_='foreignkey')
    op.drop_column('bidang', 'bundle_hd_id')
    op.create_table('category_dokumen',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('fg_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], name='category_dokumen_created_by_id_fkey'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], name='category_dokumen_updated_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='category_dokumen_pkey')
    )
    op.create_index('ix_category_dokumen_id', 'category_dokumen', ['id'], unique=False)
    # ### end Alembic commands ###
