"""invoce, termin

Revision ID: 57d6da9703f2
Revises: a243e4993bff
Create Date: 2023-09-20 19:59:27.281886

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '57d6da9703f2'
down_revision = 'a243e4993bff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('termin', sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('termin', sa.Column('is_void', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('termin', 'is_void')
    op.drop_column('termin', 'code')
    # ### end Alembic commands ###
