"""5_tanggal_tanda_terima_jadi_date

Revision ID: 588317bf844f
Revises: ca7c50c9ff57
Create Date: 2023-07-07 15:00:08.544036

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '588317bf844f'
down_revision = 'ca7c50c9ff57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
