"""36 delete planing ttn id dan luas surat ttn

Revision ID: 58fe4c029c3f
Revises: a77ed7c65af4
Create Date: 2023-06-20 16:27:45.780519

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '58fe4c029c3f'
down_revision = 'a77ed7c65af4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('kjb_dt_planing_ttn_id_fkey', 'kjb_dt', type_='foreignkey')
    op.drop_column('kjb_dt', 'luas_surat_ttn')
    op.drop_column('kjb_dt', 'planing_ttn_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kjb_dt', sa.Column('planing_ttn_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('kjb_dt', sa.Column('luas_surat_ttn', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.create_foreign_key('kjb_dt_planing_ttn_id_fkey', 'kjb_dt', 'planing', ['planing_ttn_id'], ['id'])
    # ### end Alembic commands ###
