"""import log delete

Revision ID: 5cd52250fc2c
Revises: b2e1cfa19cd5
Create Date: 2023-07-20 15:42:05.562775

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '5cd52250fc2c'
down_revision = 'b2e1cfa19cd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_log', 'start_row')
    op.drop_column('import_log', 'end_row')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_log', sa.Column('end_row', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('import_log', sa.Column('start_row', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
