"""_m_0004

Revision ID: 5e0ee09a382e
Revises: 5fd36c433a26
Create Date: 2023-10-12 15:21:14.110996

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '5e0ee09a382e'
down_revision = '5fd36c433a26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('termin_bayar',
    sa.Column('termin_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rekening_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['rekening_id'], ['rekening.id'], ),
    sa.ForeignKeyConstraint(['termin_id'], ['termin.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_termin_bayar_id'), 'termin_bayar', ['id'], unique=False)
    op.add_column('termin', sa.Column('manager_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('termin', sa.Column('sales_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('termin', sa.Column('mediator', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'termin', 'sales', ['sales_id'], ['id'])
    op.create_foreign_key(None, 'termin', 'manager', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'termin', type_='foreignkey')
    op.drop_constraint(None, 'termin', type_='foreignkey')
    op.drop_column('termin', 'mediator')
    op.drop_column('termin', 'sales_id')
    op.drop_column('termin', 'manager_id')
    op.drop_index(op.f('ix_termin_bayar_id'), table_name='termin_bayar')
    op.drop_table('termin_bayar')
    # ### end Alembic commands ###
