"""_m_0009

Revision ID: 5f1a10840139
Revises: 63638b461678
Create Date: 2023-10-20 16:11:23.171772

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '5f1a10840139'
down_revision = '63638b461678'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giro', sa.Column('nomor_giro', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'giro', ['nomor_giro'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'giro', type_='unique')
    op.drop_column('giro', 'nomor_giro')
    # ### end Alembic commands ###
