"""_m_0013

Revision ID: 5f80d2de2d87
Revises: 4cfa40d3894e
Create Date: 2023-10-24 19:02:38.900307

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '5f80d2de2d87'
down_revision = '4cfa40d3894e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bidang_komponen_biaya', sa.Column('satuan_bayar', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('bidang_komponen_biaya', sa.Column('satuan_harga', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('bidang_komponen_biaya', sa.Column('amount', sa.Numeric(scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bidang_komponen_biaya', 'amount')
    op.drop_column('bidang_komponen_biaya', 'satuan_harga')
    op.drop_column('bidang_komponen_biaya', 'satuan_bayar')
    # ### end Alembic commands ###
