"""14_Update Desa Table, field last for Id Bidang

Revision ID: 60d6972c7370
Revises: b4326dc4bf75
Create Date: 2023-05-02 15:46:26.027510

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '60d6972c7370'
down_revision = 'b4326dc4bf75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('desa', sa.Column('last', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('desa', 'last')
    # ### end Alembic commands ###
