"""_m_0002

Revision ID: 60e71a0c3151
Revises: 66cfed1bfb2d
Create Date: 2023-10-12 11:21:38.788410

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '60e71a0c3151'
down_revision = '66cfed1bfb2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('termin', sa.Column('sales_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'termin', 'sales', ['sales_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'termin', type_='foreignkey')
    op.drop_column('termin', 'sales_id')
    # ### end Alembic commands ###
