"""_m_093

Revision ID: 61bd297e8408
Revises: 22667a5f60b2
Create Date: 2024-03-24 11:23:54.529614

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '61bd297e8408'
down_revision = '22667a5f60b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beban_biaya', sa.Column('is_exclude_printout', sa.Boolean(), nullable=True))
    op.add_column('bidang_komponen_biaya', sa.Column('order_number', sa.Integer(), nullable=True))
    op.add_column('spk', sa.Column('order_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spk', 'order_number')
    op.drop_column('bidang_komponen_biaya', 'order_number')
    op.drop_column('beban_biaya', 'is_exclude_printout')
    # ### end Alembic commands ###
