"""_m_090

Revision ID: 62f231715ac3
Revises: 16ec76244f2b
Create Date: 2024-03-23 23:15:35.505610

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '62f231715ac3'
down_revision = '16ec76244f2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'payment_method',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payment', 'pay_to',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('payment_termin_id_fkey', 'payment', type_='foreignkey')
    op.drop_column('payment', 'termin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('termin_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('payment_termin_id_fkey', 'payment', 'termin', ['termin_id'], ['id'])
    op.alter_column('payment', 'pay_to',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payment', 'payment_method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
