"""_m_0008

Revision ID: 63638b461678
Revises: 962ffd1ad3fa
Create Date: 2023-10-19 11:58:30.006630

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '63638b461678'
down_revision = '962ffd1ad3fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kjb_hd', 'remark',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kjb_hd', 'remark',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
