"""_m_0001

Revision ID: 66cfed1bfb2d
Revises: 
Create Date: 2023-10-12 11:19:45.915314

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '66cfed1bfb2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('termin', sa.Column('manager_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('termin', sa.Column('mediator', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'termin', 'manager', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'termin', type_='foreignkey')
    op.drop_column('termin', 'mediator')
    op.drop_column('termin', 'manager_id')
    # ### end Alembic commands ###
