"""_m_0046

Revision ID: 676be63e7355
Revises: 25bc71956231
Create Date: 2023-12-19 19:15:54.919324

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '676be63e7355'
down_revision = '25bc71956231'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('termin', sa.Column('void_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('termin', sa.Column('void_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('termin', sa.Column('void_at', sa.Date(), nullable=True))
    op.create_foreign_key(None, 'termin', 'worker', ['void_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'termin', type_='foreignkey')
    op.drop_column('termin', 'void_at')
    op.drop_column('termin', 'void_reason')
    op.drop_column('termin', 'void_by_id')
    # ### end Alembic commands ###
