"""27 AGUSTUS 2024 16:50 - Kategori Id on Closing

Revision ID: 6bdbe3ee6f41
Revises: 964fcbadb184
Create Date: 2024-08-27 16:50:37.557611

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '6bdbe3ee6f41'
down_revision = '964fcbadb184'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
