"""22_revisi field tipe bidang pada table bidang

Revision ID: 6c00dc25d5c2
Revises: 1c2ec0113e4d
Create Date: 2023-05-10 11:38:32.719985

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '6c00dc25d5c2'
down_revision = '1c2ec0113e4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bidang', sa.Column('tipe_bidang', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bidang', 'tipe_bidang')
    # ### end Alembic commands ###
