"""2 September 2024 11:04 - add field peminjaman_header

Revision ID: 7256be717041
Revises: 28d6f97e427f
Create Date: 2024-09-02 11:05:17.173252

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7256be717041'
down_revision = '28d6f97e427f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peminjaman_header', sa.Column('project_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('peminjaman_header', sa.Column('desa_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.alter_column('peminjaman_header', 'ptsk_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_constraint('peminjaman_header_planing_id_fkey', 'peminjaman_header', type_='foreignkey')
    op.create_foreign_key(None, 'peminjaman_header', 'desa', ['desa_id'], ['id'])
    op.create_foreign_key(None, 'peminjaman_header', 'project', ['project_id'], ['id'])
    op.drop_column('peminjaman_header', 'planing_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peminjaman_header', sa.Column('planing_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'peminjaman_header', type_='foreignkey')
    op.drop_constraint(None, 'peminjaman_header', type_='foreignkey')
    op.create_foreign_key('peminjaman_header_planing_id_fkey', 'peminjaman_header', 'planing', ['planing_id'], ['id'])
    op.alter_column('peminjaman_header', 'ptsk_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_column('peminjaman_header', 'desa_id')
    op.drop_column('peminjaman_header', 'project_id')
    # ### end Alembic commands ###
