"""tanggal transaksi

Revision ID: 73f1fa212c67
Revises: e50ae0056cec
Create Date: 2023-09-25 10:43:33.579944

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '73f1fa212c67'
down_revision = 'e50ae0056cec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('termin', sa.Column('tanggal_transaksi', sa.Date(), nullable=True))
    op.drop_column('termin', 'rencana_transaksi')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('termin', sa.Column('rencana_transaksi', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('termin', 'tanggal_transaksi')
    # ### end Alembic commands ###
