"""_11 JULI 2024__amount netto on invoice

Revision ID: 746b7bce4df5
Revises: 4cebf85d08b7
Create Date: 2024-07-11 10:31:55.222032

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '746b7bce4df5'
down_revision = '4cebf85d08b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('amount_netto', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'amount_netto')
    # ### end Alembic commands ###
