"""order gambar ukur

Revision ID: 751315af47e4
Revises: d4ed31048ac1
Create Date: 2023-08-22 14:49:32.745589

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '751315af47e4'
down_revision = 'd4ed31048ac1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_gambar_ukur',
    sa.Column('tipe_surat', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tujuan_surat_worker_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('tujuan_surat_notaris_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['tujuan_surat_notaris_id'], ['notaris.id'], ),
    sa.ForeignKeyConstraint(['tujuan_surat_worker_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_gambar_ukur_id'), 'order_gambar_ukur', ['id'], unique=False)
    op.create_table('order_gambar_ukur_tembusan',
    sa.Column('order_gambar_ukur_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tembusan_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['order_gambar_ukur_id'], ['order_gambar_ukur.id'], ),
    sa.ForeignKeyConstraint(['tembusan_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_gambar_ukur_tembusan_id'), 'order_gambar_ukur_tembusan', ['id'], unique=False)
    op.create_table('order_gambar_ukur_bidang',
    sa.Column('order_gambar_ukur_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('bidang_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['bidang_id'], ['bidang.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['order_gambar_ukur_id'], ['order_gambar_ukur.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_gambar_ukur_bidang_id'), 'order_gambar_ukur_bidang', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_gambar_ukur_bidang_id'), table_name='order_gambar_ukur_bidang')
    op.drop_table('order_gambar_ukur_bidang')
    op.drop_index(op.f('ix_order_gambar_ukur_tembusan_id'), table_name='order_gambar_ukur_tembusan')
    op.drop_table('order_gambar_ukur_tembusan')
    op.drop_index(op.f('ix_order_gambar_ukur_id'), table_name='order_gambar_ukur')
    op.drop_table('order_gambar_ukur')
    # ### end Alembic commands ###
