"""_m_0078

Revision ID: 76d4519dceb1
Revises: e6072474d967
Create Date: 2024-03-02 00:46:44.361674

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '76d4519dceb1'
down_revision = 'e6072474d967'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('import_bidang_paid')
    op.add_column('bidang', sa.Column('parent_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'bidang', 'bidang', ['parent_id'], ['id'])
    op.add_column('dokumen', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('dokumen', sa.Column('is_exclude_printout', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dokumen', 'is_exclude_printout')
    op.drop_column('dokumen', 'is_active')
    op.drop_constraint(None, 'bidang', type_='foreignkey')
    op.drop_column('bidang', 'parent_id')
    op.create_table('import_bidang_paid',
    sa.Column('id_bidang_lama', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('no_tahap', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('luas_bayar', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('harga_transaksi', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('paid_amount', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('cutoff_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_bidang_lama', name='import_bidang_paid_pkey')
    )
    # ### end Alembic commands ###
