"""_m_0071

Revision ID: 7799b0b7777c
Revises: 541b20abbff0
Create Date: 2024-02-02 11:11:09.846308

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '7799b0b7777c'
down_revision = '541b20abbff0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spk', sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spk', 'file_path')
    # ### end Alembic commands ###
