"""luas_bayar

Revision ID: 77ce123faec8
Revises: 8468b4b3538c
Create Date: 2023-09-07 16:53:44.581014

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '77ce123faec8'
down_revision = '8468b4b3538c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bidang', sa.Column('luas_bayar', sa.Numeric(scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bidang', 'luas_bayar')
    # ### end Alembic commands ###
