"""_m_0011

Revision ID: 7a2820909447
Revises: 90e0c48ffd0a
Create Date: 2023-10-20 18:49:10.561637

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a2820909447'
down_revision = '90e0c48ffd0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bidang', sa.Column('geom_ori', geoalchemy2.types.Geometry(from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    #op.create_index('idx_bidang_geom_ori', 'bidang', ['geom_ori'], unique=False, postgresql_using='gist')
    op.add_column('bidang_overlap', sa.Column('geom_temp', geoalchemy2.types.Geometry(from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.alter_column('bidang_overlap', 'parent_bidang_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('bidang_overlap', 'parent_bidang_intersect_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('bidang_overlap', 'luas',
               existing_type=sa.NUMERIC(),
               nullable=True)
    #op.create_index('idx_bidang_overlap_geom_temp', 'bidang_overlap', ['geom_temp'], unique=False, postgresql_using='gist')
    op.add_column('giro', sa.Column('nomor_giro', sa.String(), nullable=True))
    op.add_column('giro', sa.Column('from_master', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'giro', ['nomor_giro'])
    op.add_column('hasil_peta_lokasi', sa.Column('sub_project_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'hasil_peta_lokasi', 'sub_project', ['sub_project_id'], ['id'])
    op.alter_column('kjb_hd', 'remark',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kjb_hd', 'remark',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'hasil_peta_lokasi', type_='foreignkey')
    op.drop_column('hasil_peta_lokasi', 'sub_project_id')
    op.drop_constraint(None, 'giro', type_='unique')
    op.drop_column('giro', 'from_master')
    op.drop_column('giro', 'nomor_giro')
    op.drop_index('idx_bidang_overlap_geom_temp', table_name='bidang_overlap', postgresql_using='gist')
    op.alter_column('bidang_overlap', 'luas',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('bidang_overlap', 'parent_bidang_intersect_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('bidang_overlap', 'parent_bidang_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_column('bidang_overlap', 'geom_temp')
    op.drop_index('idx_bidang_geom_ori', table_name='bidang', postgresql_using='gist')
    op.drop_column('bidang', 'geom_ori')
    # ### end Alembic commands ###
