"""luas bayar overlap

Revision ID: 7dba902281ab
Revises: 162e2b69e59e
Create Date: 2023-10-06 11:15:41.656022

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '7dba902281ab'
down_revision = '162e2b69e59e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bidang_overlap', sa.Column('luas_bayar', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bidang_overlap', 'luas_bayar')
    # ### end Alembic commands ###
