"""file path tanda terima notaris

Revision ID: 85a7219a6d06
Revises: 4d2fd5b50f59
Create Date: 2023-07-31 20:13:43.134815

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '85a7219a6d06'
down_revision = '4d2fd5b50f59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tanda_terima_notaris_dt', sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tanda_terima_notaris_dt', 'file_path')
    # ### end Alembic commands ###
