"""kjb termin in spk

Revision ID: 85f932f43fe2
Revises: 
Create Date: 2023-09-26 13:07:54.223265

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '85f932f43fe2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spk', sa.Column('kjb_termin_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'spk', 'kjb_termin', ['kjb_termin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spk', type_='foreignkey')
    op.drop_column('spk', 'kjb_termin_id')
    # ### end Alembic commands ###
