"""tahap pembayaran

Revision ID: 862a361e3850
Revises: 
Create Date: 2023-09-18 15:29:10.302422

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '862a361e3850'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tahap',
    sa.Column('nomor_tahap', sa.Integer(), nullable=False),
    sa.Column('planing_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('ptsk_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('penampung_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['penampung_id'], ['ptsk.id'], ),
    sa.ForeignKeyConstraint(['planing_id'], ['planing.id'], ),
    sa.ForeignKeyConstraint(['ptsk_id'], ['ptsk.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tahap_id'), 'tahap', ['id'], unique=False)
    op.create_table('tahap_detail',
    sa.Column('tahap_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('bidang_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('is_void', sa.Boolean(), nullable=False),
    sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['bidang_id'], ['bidang.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['tahap_id'], ['tahap.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tahap_detail_id'), 'tahap_detail', ['id'], unique=False)
    op.add_column('bidang', sa.Column('satuan', sa.Numeric(scale=2), nullable=True))
    op.add_column('bidang', sa.Column('satuan_akta', sa.Numeric(scale=2), nullable=True))
    op.add_column('section', sa.Column('last_tahap', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section', 'last_tahap')
    op.drop_column('bidang', 'satuan_akta')
    op.drop_column('bidang', 'satuan')
    op.drop_index(op.f('ix_tahap_detail_id'), table_name='tahap_detail')
    op.drop_table('tahap_detail')
    op.drop_index(op.f('ix_tahap_id'), table_name='tahap')
    op.drop_table('tahap')
    # ### end Alembic commands ###
