"""date

Revision ID: 88af9f6bb1ac
Revises: cbf9f3de7575
Create Date: 2023-08-04 15:26:38.127183

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '88af9f6bb1ac'
down_revision = 'cbf9f3de7575'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
