"""getall

Revision ID: 88e87704344d
Revises: c24f8ab68473
Create Date: 2023-08-15 11:49:52.424305

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '88e87704344d'
down_revision = 'c24f8ab68473'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bidang_overlap',
    sa.Column('geom', geoalchemy2.types.Geometry(from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent_bidang_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('parent_bidang_intersect_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('luas', sa.Numeric(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    #op.create_index('idx_bidang_overlap_geom', 'bidang_overlap', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_bidang_overlap_id'), 'bidang_overlap', ['id'], unique=False)
    op.alter_column('hasil_peta_lokasi', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('hasil_peta_lokasi_detail', sa.Column('bidang_overlap_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'hasil_peta_lokasi_detail', 'bidang_overlap', ['bidang_overlap_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hasil_peta_lokasi_detail', type_='foreignkey')
    op.drop_column('hasil_peta_lokasi_detail', 'bidang_overlap_id')
    op.alter_column('hasil_peta_lokasi', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_bidang_overlap_id'), table_name='bidang_overlap')
    op.drop_index('idx_bidang_overlap_geom', table_name='bidang_overlap', postgresql_using='gist')
    op.drop_table('bidang_overlap')
    # ### end Alembic commands ###
