"""komponen biaya dan invoice

Revision ID: 8a3d792dd3e1
Revises: 3fffc042a619
Create Date: 2023-09-19 15:59:41.720731

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a3d792dd3e1'
down_revision = '3fffc042a619'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_spk_beban_biaya_id', table_name='spk_beban_biaya')
    op.drop_table('spk_beban_biaya')
    op.add_column('bidang_komponen_biaya', sa.Column('beban_pembeli', sa.Boolean(), nullable=True))
    op.add_column('bidang_komponen_biaya', sa.Column('is_use', sa.Boolean(), nullable=True))
    op.add_column('bidang_komponen_biaya', sa.Column('is_paid', sa.Boolean(), nullable=True))
    op.drop_column('bidang_komponen_biaya', 'tanggungan_biaya')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bidang_komponen_biaya', sa.Column('tanggungan_biaya', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('bidang_komponen_biaya', 'is_paid')
    op.drop_column('bidang_komponen_biaya', 'is_use')
    op.drop_column('bidang_komponen_biaya', 'beban_pembeli')
    op.create_table('spk_beban_biaya',
    sa.Column('spk_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('beban_biaya_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('beban_pembeli', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['beban_biaya_id'], ['beban_biaya.id'], name='spk_beban_biaya_beban_biaya_id_fkey'),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], name='spk_beban_biaya_created_by_id_fkey'),
    sa.ForeignKeyConstraint(['spk_id'], ['spk.id'], name='spk_beban_biaya_spk_id_fkey'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], name='spk_beban_biaya_updated_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='spk_beban_biaya_pkey')
    )
    op.create_index('ix_spk_beban_biaya_id', 'spk_beban_biaya', ['id'], unique=False)
    # ### end Alembic commands ###
