"""__spk is draft

Revision ID: 8b9cf103d987
Revises: fe88386c8ace
Create Date: 2024-06-06 15:44:31.510133

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b9cf103d987'
down_revision = 'fe88386c8ace'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_termin_rfp_payment_id', table_name='termin_rfp_payment')
    op.drop_table('termin_rfp_payment')
    op.add_column('spk', sa.Column('is_draft', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spk', 'is_draft')
    op.create_table('termin_rfp_payment',
    sa.Column('termin_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('rfp_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('payment_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], name='termin_rfp_payment_created_by_id_fkey'),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], name='termin_rfp_payment_payment_id_fkey'),
    sa.ForeignKeyConstraint(['termin_id'], ['termin.id'], name='termin_rfp_payment_termin_id_fkey'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], name='termin_rfp_payment_updated_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='termin_rfp_payment_pkey')
    )
    op.create_index('ix_termin_rfp_payment_id', 'termin_rfp_payment', ['id'], unique=False)
    # ### end Alembic commands ###
