"""_m_100

Revision ID: 8cc980672ec2
Revises: 01ead61ce4e6
Create Date: 2024-04-01 19:06:21.666610

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '8cc980672ec2'
down_revision = '01ead61ce4e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('termin_bayar', sa.Column('activity', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('termin_bayar', 'activity')
    # ### end Alembic commands ###
