"""_m_0067

Revision ID: 8dac6356ba81
Revises: 37356bb172f3
Create Date: 2024-01-30 17:43:03.948720

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '8dac6356ba81'
down_revision = '37356bb172f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hasil_peta_lokasi', sa.Column('tanggal_kirim_berkas', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hasil_peta_lokasi', 'tanggal_kirim_berkas')
    # ### end Alembic commands ###
