"""_m_0010

Revision ID: 90e0c48ffd0a
Revises: 5f1a10840139
Create Date: 2023-10-20 16:50:33.223994

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '90e0c48ffd0a'
down_revision = '5f1a10840139'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giro', sa.Column('from_master', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('giro', 'from_master')
    # ### end Alembic commands ###
