"""recreate bidang

Revision ID: 912721803f79
Revises: 192afe7b451a
Create Date: 2023-07-24 11:20:58.741510

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '912721803f79'
down_revision = '192afe7b451a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bidang', sa.Column('pemilik_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('bidang', sa.Column('jenis_bidang', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('bidang', sa.Column('group', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('bidang', sa.Column('jenis_alashak', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('bidang', sa.Column('jenis_surat_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('bidang', sa.Column('alashak', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('bidang', sa.Column('kategori_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('bidang', sa.Column('kategori_sub_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('bidang', sa.Column('kategori_proyek_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('bidang', sa.Column('penampung_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('bidang', sa.Column('manager_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('bidang', sa.Column('sales_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('bidang', sa.Column('madiator', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('bidang', sa.Column('telepon_mediator', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('bidang', sa.Column('notaris_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('bidang', sa.Column('tahap', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('bidang', sa.Column('informasi_tambahan', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('bidang', sa.Column('luas_ukur', sa.Numeric(), nullable=True))
    op.add_column('bidang', sa.Column('luas_gu_perorangan', sa.Numeric(), nullable=True))
    op.add_column('bidang', sa.Column('luas_gu_pt', sa.Numeric(), nullable=True))
    op.add_column('bidang', sa.Column('luas_nett', sa.Numeric(), nullable=True))
    op.add_column('bidang', sa.Column('luas_clear', sa.Numeric(), nullable=True))
    op.add_column('bidang', sa.Column('luas_pbt_perorangan', sa.Numeric(), nullable=True))
    op.add_column('bidang', sa.Column('luas_pbt_pt', sa.Numeric(), nullable=True))
    op.alter_column('bidang', 'no_peta',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bidang', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bidang', 'luas_surat',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.drop_constraint('bidang_jenis_lahan_id_fkey', 'bidang', type_='foreignkey')
    op.create_foreign_key(None, 'bidang', 'manager', ['manager_id'], ['id'])
    op.create_foreign_key(None, 'bidang', 'sales', ['sales_id'], ['id'])
    op.create_foreign_key(None, 'bidang', 'kategori_sub', ['kategori_sub_id'], ['id'])
    op.create_foreign_key(None, 'bidang', 'pemilik', ['pemilik_id'], ['id'])
    op.create_foreign_key(None, 'bidang', 'notaris', ['notaris_id'], ['id'])
    op.create_foreign_key(None, 'bidang', 'kategori_proyek', ['kategori_proyek_id'], ['id'])
    op.create_foreign_key(None, 'bidang', 'kategori', ['kategori_id'], ['id'])
    op.create_foreign_key(None, 'bidang', 'jenis_surat', ['jenis_surat_id'], ['id'])
    op.create_foreign_key(None, 'bidang', 'ptsk', ['penampung_id'], ['id'])
    op.drop_column('bidang', 'tipe_proses')
    op.drop_column('bidang', 'jenis_dokumen')
    op.drop_column('bidang', 'nama_pemilik')
    op.drop_column('bidang', 'tipe_bidang')
    op.drop_column('bidang', 'jenis_lahan_id')
    op.drop_column('bidang', 'alas_hak')
    op.drop_column('bidang', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bidang', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bidang', sa.Column('alas_hak', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('bidang', sa.Column('jenis_lahan_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('bidang', sa.Column('tipe_bidang', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bidang', sa.Column('nama_pemilik', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bidang', sa.Column('jenis_dokumen', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bidang', sa.Column('tipe_proses', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bidang', type_='foreignkey')
    op.drop_constraint(None, 'bidang', type_='foreignkey')
    op.drop_constraint(None, 'bidang', type_='foreignkey')
    op.drop_constraint(None, 'bidang', type_='foreignkey')
    op.drop_constraint(None, 'bidang', type_='foreignkey')
    op.drop_constraint(None, 'bidang', type_='foreignkey')
    op.drop_constraint(None, 'bidang', type_='foreignkey')
    op.drop_constraint(None, 'bidang', type_='foreignkey')
    op.drop_constraint(None, 'bidang', type_='foreignkey')
    op.create_foreign_key('bidang_jenis_lahan_id_fkey', 'bidang', 'jenis_lahan', ['jenis_lahan_id'], ['id'])
    op.alter_column('bidang', 'luas_surat',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('bidang', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bidang', 'no_peta',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('bidang', 'luas_pbt_pt')
    op.drop_column('bidang', 'luas_pbt_perorangan')
    op.drop_column('bidang', 'luas_clear')
    op.drop_column('bidang', 'luas_nett')
    op.drop_column('bidang', 'luas_gu_pt')
    op.drop_column('bidang', 'luas_gu_perorangan')
    op.drop_column('bidang', 'luas_ukur')
    op.drop_column('bidang', 'informasi_tambahan')
    op.drop_column('bidang', 'tahap')
    op.drop_column('bidang', 'notaris_id')
    op.drop_column('bidang', 'telepon_mediator')
    op.drop_column('bidang', 'madiator')
    op.drop_column('bidang', 'sales_id')
    op.drop_column('bidang', 'manager_id')
    op.drop_column('bidang', 'penampung_id')
    op.drop_column('bidang', 'kategori_proyek_id')
    op.drop_column('bidang', 'kategori_sub_id')
    op.drop_column('bidang', 'kategori_id')
    op.drop_column('bidang', 'alashak')
    op.drop_column('bidang', 'jenis_surat_id')
    op.drop_column('bidang', 'jenis_alashak')
    op.drop_column('bidang', 'group')
    op.drop_column('bidang', 'jenis_bidang')
    op.drop_column('bidang', 'pemilik_id')
    # ### end Alembic commands ###
