"""3_Rename field gps table

Revision ID: 93b845b5b9d2
Revises: 3dc206eb0c6d
Create Date: 2023-04-14 11:38:50.505792

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '93b845b5b9d2'
down_revision = '3dc206eb0c6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gps', sa.Column('penunjuk', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('gps', 'petunjuk')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gps', sa.Column('petunjuk', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('gps', 'penunjuk')
    # ### end Alembic commands ###
