"""_m_097

Revision ID: 941f5a932037
Revises: b10732682cf9
Create Date: 2024-03-27 09:45:47.321318

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '941f5a932037'
down_revision = 'b10732682cf9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beban_biaya', sa.Column('default_spk_girik', sa.Boolean(), nullable=True))
    op.add_column('beban_biaya', sa.Column('default_spk_sertifikat', sa.Boolean(), nullable=True))
    op.add_column('bidang_komponen_biaya', sa.Column('is_exclude_spk', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bidang_komponen_biaya', 'is_exclude_spk')
    op.drop_column('beban_biaya', 'default_spk_sertifikat')
    op.drop_column('beban_biaya', 'default_spk_girik')
    # ### end Alembic commands ###
