"""_m_0032

Revision ID: 9545689065df
Revises: 05459b76890d
Create Date: 2023-11-29 15:10:45.657610

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '9545689065df'
down_revision = '05459b76890d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utj_khusus', sa.Column('termin_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.create_foreign_key(None, 'utj_khusus', 'termin', ['termin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'utj_khusus', type_='foreignkey')
    op.drop_column('utj_khusus', 'termin_id')
    # ### end Alembic commands ###
