"""27 Agustus 2024 Add Table Peminjaman

Revision ID: 964fcbadb184
Revises: f18f2631feaf
Create Date: 2024-08-27 10:27:24.123691

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '964fcbadb184'
down_revision = 'f18f2631feaf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peminjaman_header',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('nomor_perjanjian', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tanggal_perjanjian', sa.DateTime(), nullable=True),
    sa.Column('planing_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('ptsk_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('kategori', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tanda_tangan_lurah', sa.Boolean(), nullable=True),
    sa.Column('produktivitas_tanah', sa.Boolean(), nullable=True),
    sa.Column('gratis', sa.Boolean(), nullable=True),
    sa.Column('sewa', sa.Boolean(), nullable=True),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['planing_id'], ['planing.id'], ),
    sa.ForeignKeyConstraint(['ptsk_id'], ['ptsk.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peminjaman_header_id'), 'peminjaman_header', ['id'], unique=False)
    op.create_table('peminjaman_penggarap',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alamat', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nomor_ktp', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nomor_handphone', sa.Integer(), nullable=True),
    sa.Column('peminjaman_header_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['peminjaman_header_id'], ['peminjaman_header.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peminjaman_penggarap_id'), 'peminjaman_penggarap', ['id'], unique=False)
    op.create_table('peminjaman_bidang',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('bidang_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('peminjaman_header_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['bidang_id'], ['bidang.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['peminjaman_header_id'], ['peminjaman_header.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peminjaman_bidang_id'), 'peminjaman_bidang', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_peminjaman_bidang_id'), table_name='peminjaman_bidang')
    op.drop_table('peminjaman_bidang')
    op.drop_index(op.f('ix_peminjaman_penggarap_id'), table_name='peminjaman_penggarap')
    op.drop_table('peminjaman_penggarap')
    op.drop_index(op.f('ix_peminjaman_header_id'), table_name='peminjaman_header')
    op.drop_table('peminjaman_header')
    # ### end Alembic commands ###
