"""30 pemilik id in kontak

Revision ID: 96ddf6affa74
Revises: b4e8d04a5f81
Create Date: 2023-06-07 18:03:55.842969

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '96ddf6affa74'
down_revision = 'b4e8d04a5f81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kontak', sa.Column('pemilik_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.create_foreign_key(None, 'kontak', 'pemilik', ['pemilik_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kontak', type_='foreignkey')
    op.drop_column('kontak', 'pemilik_id')
    # ### end Alembic commands ###
