"""32 Notaris dan Tanda Terima Notaris Hd

Revision ID: 9f0c08b05972
Revises: cff82ad796f7
Create Date: 2023-06-13 14:49:56.873718

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '9f0c08b05972'
down_revision = 'cff82ad796f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notaris',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notaris_id'), 'notaris', ['id'], unique=False)
    op.create_table('tanda_terima_notaris_hd',
    sa.Column('kjb_hd_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('kjb_dt_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('jenis_alashak', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('jenis_surat_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tanggal_tanda_terima', sa.DateTime(), nullable=True),
    sa.Column('nomor_tanda_terima', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kategori_penjual', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notaris_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('planing_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('luas_surat', sa.Numeric(), nullable=False),
    sa.Column('status_valid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status_peta_lokasi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jenis_surat_id'], ['jenis_surat.id'], ),
    sa.ForeignKeyConstraint(['kjb_dt_id'], ['kjb_dt.id'], ),
    sa.ForeignKeyConstraint(['kjb_hd_id'], ['kjb_hd.id'], ),
    sa.ForeignKeyConstraint(['notaris_id'], ['notaris.id'], ),
    sa.ForeignKeyConstraint(['planing_id'], ['planing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tanda_terima_notaris_hd_id'), 'tanda_terima_notaris_hd', ['id'], unique=False)
    op.add_column('kjb_dt', sa.Column('bundle_hd_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'kjb_dt', 'bundle_hd', ['bundle_hd_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kjb_dt', type_='foreignkey')
    op.drop_column('kjb_dt', 'bundle_hd_id')
    op.drop_index(op.f('ix_tanda_terima_notaris_hd_id'), table_name='tanda_terima_notaris_hd')
    op.drop_table('tanda_terima_notaris_hd')
    op.drop_index(op.f('ix_notaris_id'), table_name='notaris')
    op.drop_table('notaris')
    # ### end Alembic commands ###
