"""bidang

Revision ID: 9f4fe237ddd9
Revises: 912721803f79
Create Date: 2023-07-24 14:49:08.809078

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '9f4fe237ddd9'
down_revision = '912721803f79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bidang', sa.Column('mediator', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('bidang', 'madiator')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bidang', sa.Column('madiator', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('bidang', 'mediator')
    # ### end Alembic commands ###
