"""_import_history_update_bidang

Revision ID: a0d919f9ab15
Revises: 1cd8af87be74
Create Date: 2024-05-27 18:11:48.783574

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'a0d919f9ab15'
down_revision = '1cd8af87be74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
