"""add code on desa

Revision ID: a926073b9de5
Revises: d221a60efca9
Create Date: 2023-04-05 10:53:46.121726

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'a926073b9de5'
down_revision = 'd221a60efca9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('desa', sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('desa', 'code')
    # ### end Alembic commands ###
