"""order gu with kjb_dt

Revision ID: abf06262d572
Revises: 
Create Date: 2023-09-14 16:59:30.721252

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'abf06262d572'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_gambar_ukur', 'status_bidang',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('order_gambar_ukur_bidang', sa.Column('kjb_dt_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.drop_constraint('order_gambar_ukur_bidang_bidang_id_fkey', 'order_gambar_ukur_bidang', type_='foreignkey')
    op.create_foreign_key(None, 'order_gambar_ukur_bidang', 'kjb_dt', ['kjb_dt_id'], ['id'])
    op.drop_column('order_gambar_ukur_bidang', 'bidang_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_gambar_ukur_bidang', sa.Column('bidang_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order_gambar_ukur_bidang', type_='foreignkey')
    op.create_foreign_key('order_gambar_ukur_bidang_bidang_id_fkey', 'order_gambar_ukur_bidang', 'bidang', ['bidang_id'], ['id'])
    op.drop_column('order_gambar_ukur_bidang', 'kjb_dt_id')
    op.alter_column('order_gambar_ukur', 'status_bidang',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
