"""_m_0035

Revision ID: adfaf46a0279
Revises: 86859e15a033
Create Date: 2023-12-05 11:14:14.023728

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'adfaf46a0279'
down_revision = '86859e15a033'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bidang', 'id_bidang',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_unique_constraint(None, 'bidang', ['id_bidang_lama'])
    op.create_unique_constraint(None, 'bidang', ['id_bidang'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bidang', type_='unique')
    op.drop_constraint(None, 'bidang', type_='unique')
    op.alter_column('bidang', 'id_bidang',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
