"""_m_0063

Revision ID: b002df19cad0
Revises: 4e23f43935b0
Create Date: 2024-01-29 13:57:54.305504

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'b002df19cad0'
down_revision = '4e23f43935b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bidang', sa.Column('luas_produk', sa.Numeric(), nullable=True))
    op.alter_column('request_peta_lokasi', 'remark',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_peta_lokasi', 'remark',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('bidang', 'luas_produk')
    # ### end Alembic commands ###
