"""end row

Revision ID: b2e1cfa19cd5
Revises: d8417ee10011
Create Date: 2023-07-18 21:24:54.698872

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'b2e1cfa19cd5'
down_revision = 'd8417ee10011'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_log', sa.Column('end_row', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_log', 'end_row')
    # ### end Alembic commands ###
