"""26 Agustus 2024 11:16 - ADD PROJECT ID ON KJB

Revision ID: b63a5cd23755
Revises: 4845deb2dc05
Create Date: 2024-08-26 11:33:32.497559

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'b63a5cd23755'
down_revision = '4845deb2dc05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kjb_hd', sa.Column('project_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'kjb_hd', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kjb_hd', type_='foreignkey')
    op.drop_column('kjb_hd', 'project_id')
    # ### end Alembic commands ###
