"""order gu with kjb_dt

Revision ID: b9b404ea9031
Revises: e5926eca303c
Create Date: 2023-09-14 13:21:25.965199

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'b9b404ea9031'
down_revision = 'e5926eca303c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_gambar_ukur', 'status_bidang',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_gambar_ukur', 'status_bidang',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
