"""_m_0023

Revision ID: b9ce5bac8ccc
Revises: b82852602cbe
Create Date: 2023-11-21 15:47:03.145157

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'b9ce5bac8ccc'
down_revision = 'b82852602cbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beban_biaya', sa.Column('is_edit', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beban_biaya', 'is_edit')
    # ### end Alembic commands ###
