"""10_tanggal_request_petlok_jadi_date_only

Revision ID: bfd8385f2ee2
Revises: 1eed5d18c385
Create Date: 2023-07-11 12:05:50.387399

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'bfd8385f2ee2'
down_revision = '1eed5d18c385'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
