"""1_Create Draft table

Revision ID: c0577d2b7ecf
Revises: 28ce13afbc38
Create Date: 2023-04-13 15:12:40.346406

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c0577d2b7ecf'
down_revision = '28ce13afbc38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft',
    sa.Column('geom', geoalchemy2.types.Geometry(from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('rincik_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rincik_id'], ['rincik.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_draft_geom', 'draft', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_draft_id'), 'draft', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_draft_id'), table_name='draft')
    op.drop_index('idx_draft_geom', table_name='draft', postgresql_using='gist')
    op.drop_table('draft')
    # ### end Alembic commands ###
