"""spk bebanbiaya dan kelengkapan dokumen

Revision ID: c173eec79f04
Revises: de3056599d5e
Create Date: 2023-09-04 15:25:33.312415

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c173eec79f04'
down_revision = 'de3056599d5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spk_beban_biaya',
    sa.Column('spk_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('beban_biaya_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('beban_pembeli', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['beban_biaya_id'], ['beban_biaya.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['spk_id'], ['spk.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spk_beban_biaya_id'), 'spk_beban_biaya', ['id'], unique=False)
    op.create_table('spk_kelengkapan_dokumen',
    sa.Column('spk_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('bundle_dt_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tanggapan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['bundle_dt_id'], ['bundle_dt.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['spk_id'], ['spk.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spk_kelengkapan_dokumen_id'), 'spk_kelengkapan_dokumen', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spk_kelengkapan_dokumen_id'), table_name='spk_kelengkapan_dokumen')
    op.drop_table('spk_kelengkapan_dokumen')
    op.drop_index(op.f('ix_spk_beban_biaya_id'), table_name='spk_beban_biaya')
    op.drop_table('spk_beban_biaya')
    # ### end Alembic commands ###
