"""code invoice

Revision ID: c1b5c93a653c
Revises: 0dd65650b346
Create Date: 2023-10-10 11:23:45.989362

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c1b5c93a653c'
down_revision = '0dd65650b346'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'code')
    # ### end Alembic commands ###
