"""draft

Revision ID: c24f8ab68473
Revises: 3745796e35fd
Create Date: 2023-08-14 17:49:56.028555

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c24f8ab68473'
down_revision = '3745796e35fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft_detail', sa.Column('luas', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draft_detail', 'luas')
    # ### end Alembic commands ###
