"""hasil petlok

Revision ID: c2850c158469
Revises: f1532bdbdd39
Create Date: 2023-08-11 18:25:57.074421

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2850c158469'
down_revision = 'f1532bdbdd39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('draft_detail', 'draft_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('draft_detail', 'draft_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
