"""26 Agustus 2024 14:02 - ADD KAT LAHAN ON BID

Revision ID: c514c18995b0
Revises: b63a5cd23755
Create Date: 2024-08-26 14:03:34.565740

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c514c18995b0'
down_revision = 'b63a5cd23755'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bidang', sa.Column('kategori_lahan', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('bidangorigin', sa.Column('kategori_lahan', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bidangorigin', 'kategori_lahan')
    op.drop_column('bidang', 'kategori_lahan')
    # ### end Alembic commands ###
