"""_m_0029

Revision ID: c64789e38ca0
Revises: a8ee69645cb2
Create Date: 2023-11-27 16:36:05.552991

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c64789e38ca0'
down_revision = 'a8ee69645cb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spk_history', sa.Column('trans_worker_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.add_column('spk_history', sa.Column('trans_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'spk_history', 'worker', ['trans_worker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spk_history', type_='foreignkey')
    op.drop_column('spk_history', 'trans_at')
    op.drop_column('spk_history', 'trans_worker_id')
    # ### end Alembic commands ###
