"""_m_094

Revision ID: c7bc87e93289
Revises: 61bd297e8408
Create Date: 2024-03-24 11:28:12.999255

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c7bc87e93289'
down_revision = '61bd297e8408'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spk', 'order_number')
    op.add_column('spk_kelengkapan_dokumen', sa.Column('order_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spk_kelengkapan_dokumen', 'order_number')
    op.add_column('spk', sa.Column('order_number', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
