"""4_status_lanjut_petlok_di_kjb_dt

Revision ID: ca7c50c9ff57
Revises: fcc991ca40ec
Create Date: 2023-07-07 14:42:59.145845

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'ca7c50c9ff57'
down_revision = 'fcc991ca40ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kjb_dt', sa.Column('status_peta_lokasi', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('tanda_terima_notaris_hd', 'status_peta_lokasi')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tanda_terima_notaris_hd', sa.Column('status_peta_lokasi', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('kjb_dt', 'status_peta_lokasi')
    # ### end Alembic commands ###
