"""file path tanda terima notaris

Revision ID: cbf9f3de7575
Revises: 64228c9ae0c9
Create Date: 2023-08-02 09:15:53.456467

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'cbf9f3de7575'
down_revision = '64228c9ae0c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tanda_terima_notaris_hd', sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tanda_terima_notaris_hd', 'file_path')
    # ### end Alembic commands ###
