"""_m_102

Revision ID: ce6fcd30e25c
Revises: 2ab9b8fc41b6
Create Date: 2024-04-04 10:05:02.869607

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'ce6fcd30e25c'
down_revision = '2ab9b8fc41b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tahap', sa.Column('harga_standard', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tahap', 'harga_standard')
    # ### end Alembic commands ###
