"""26_add checklist dokumen

Revision ID: cffe49dc3bdf
Revises: 3a44db1b383c
Create Date: 2023-06-05 14:26:26.538905

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'cffe49dc3bdf'
down_revision = '3a44db1b383c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
