"""__takeout is ptsl and harga ptsl on kjb dt and bidang

Revision ID: d0f34c7c91f3
Revises: 3261edabb028
Create Date: 2024-06-03 16:04:01.114168

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'd0f34c7c91f3'
down_revision = '3261edabb028'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bidang', 'is_ptsl')
    op.drop_column('bidang', 'harga_ptsl')
    op.drop_column('bidangorigin', 'is_ptsl')
    op.drop_column('bidangorigin', 'harga_ptsl')
    op.drop_column('kjb_dt', 'harga_ptsl')
    op.drop_column('kjb_harga', 'harga_ptsl')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kjb_harga', sa.Column('harga_ptsl', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('kjb_dt', sa.Column('harga_ptsl', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('bidangorigin', sa.Column('harga_ptsl', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('bidangorigin', sa.Column('is_ptsl', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('bidang', sa.Column('harga_ptsl', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('bidang', sa.Column('is_ptsl', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
