"""compare type

Revision ID: d221a60efca9
Revises: caa198f27e80
Create Date: 2023-04-04 11:23:24.547331

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'd221a60efca9'
down_revision = 'caa198f27e80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planing', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('planing', 'code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planing', 'code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('planing', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
