"""hasil peta lokasi

Revision ID: d261eb76bae1
Revises: 0a36f9bd9b51
Create Date: 2023-08-16 11:10:36.422436

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd261eb76bae1'
down_revision = '0a36f9bd9b51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hasil_peta_lokasi', sa.Column('luas_nett', sa.Numeric(), nullable=True))
    op.add_column('hasil_peta_lokasi', sa.Column('luas_clear', sa.Numeric(), nullable=True))
    op.drop_constraint('hasil_peta_lokasi_ptsk_id_fkey', 'hasil_peta_lokasi', type_='foreignkey')
    op.drop_column('hasil_peta_lokasi', 'ptsk_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hasil_peta_lokasi', sa.Column('ptsk_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('hasil_peta_lokasi_ptsk_id_fkey', 'hasil_peta_lokasi', 'ptsk', ['ptsk_id'], ['id'])
    op.drop_column('hasil_peta_lokasi', 'luas_clear')
    op.drop_column('hasil_peta_lokasi', 'luas_nett')
    # ### end Alembic commands ###
