"""10_add Code on SKPT

Revision ID: d5c93f6d41d1
Revises: 57a0da9650b6
Create Date: 2023-05-02 10:21:13.660471

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'd5c93f6d41d1'
down_revision = '57a0da9650b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skpt', sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skpt', 'code')
    # ### end Alembic commands ###
