"""import log start row

Revision ID: d8417ee10011
Revises: 0d9eba7415c8
Create Date: 2023-07-18 20:17:44.644023

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'd8417ee10011'
down_revision = '0d9eba7415c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_log', sa.Column('start_row', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_log', 'start_row')
    # ### end Alembic commands ###
