"""_m_0045

Revision ID: d8d94a9f06c6
Revises: 9445d914b469
Create Date: 2023-12-15 05:43:43.316472

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'd8d94a9f06c6'
down_revision = '9445d914b469'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
