"""spk dan kawan-kawan

Revision ID: d96116b58cef
Revises: 
Create Date: 2023-09-08 17:54:17.967739

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'd96116b58cef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_report_map',
    sa.Column('report_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('desa_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('ptsk_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('bidang_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_report_map_id'), 'draft_report_map', ['id'], unique=False)
    op.create_table('giro',
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_giro_id'), 'giro', ['id'], unique=False)
    op.create_table('spk',
    sa.Column('bidang_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('jenis_bayar', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nilai', sa.Numeric(scale=2), nullable=False),
    sa.Column('satuan_bayar', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['bidang_id'], ['bidang.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spk_id'), 'spk', ['id'], unique=False)
    op.create_table('spk_beban_biaya',
    sa.Column('spk_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('beban_biaya_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('beban_pembeli', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['beban_biaya_id'], ['beban_biaya.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['spk_id'], ['spk.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spk_beban_biaya_id'), 'spk_beban_biaya', ['id'], unique=False)
    op.create_table('spk_kelengkapan_dokumen',
    sa.Column('spk_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('bundle_dt_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tanggapan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['bundle_dt_id'], ['bundle_dt.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['spk_id'], ['spk.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spk_kelengkapan_dokumen_id'), 'spk_kelengkapan_dokumen', ['id'], unique=False)
    op.add_column('bidang', sa.Column('luas_bayar', sa.Numeric(scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bidang', 'luas_bayar')
    op.drop_index(op.f('ix_spk_kelengkapan_dokumen_id'), table_name='spk_kelengkapan_dokumen')
    op.drop_table('spk_kelengkapan_dokumen')
    op.drop_index(op.f('ix_spk_beban_biaya_id'), table_name='spk_beban_biaya')
    op.drop_table('spk_beban_biaya')
    op.drop_index(op.f('ix_spk_id'), table_name='spk')
    op.drop_table('spk')
    op.drop_index(op.f('ix_giro_id'), table_name='giro')
    op.drop_table('giro')
    op.drop_index(op.f('ix_draft_report_map_id'), table_name='draft_report_map')
    op.drop_table('draft_report_map')
    # ### end Alembic commands ###
