"""satuan bayar spk

Revision ID: de3056599d5e
Revises: 9a07d12ff31f
Create Date: 2023-09-04 11:35:49.526372

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'de3056599d5e'
down_revision = '9a07d12ff31f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spk', sa.Column('satuan_bayar', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spk', 'satuan_bayar')
    # ### end Alembic commands ###
