"""_m_0048

Revision ID: df58956e3bfd
Revises: ba2a39901cb6
Create Date: 2023-12-27 10:44:29.565105

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'df58956e3bfd'
down_revision = 'ba2a39901cb6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hasil_peta_lokasi', sa.Column('luas_pbt_perorangan', sa.Numeric(), nullable=True))
    op.add_column('hasil_peta_lokasi', sa.Column('luas_pbt_pt', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hasil_peta_lokasi', 'luas_pbt_pt')
    op.drop_column('hasil_peta_lokasi', 'luas_pbt_perorangan')
    # ### end Alembic commands ###
