"""___termin rfp payment upgrade

Revision ID: e06fe62f199a
Revises: fdfcc6ce8925
Create Date: 2024-05-03 16:10:08.800854

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e06fe62f199a'
down_revision = 'fdfcc6ce8925'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('terminrfppaymentlink')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terminrfppaymentlink',
    sa.Column('termin_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('rfp_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('payment_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], name='terminrfppaymentlink_payment_id_fkey'),
    sa.ForeignKeyConstraint(['termin_id'], ['termin.id'], name='terminrfppaymentlink_termin_id_fkey'),
    sa.PrimaryKeyConstraint('termin_id', 'rfp_id', 'payment_id', name='terminrfppaymentlink_pkey')
    )
    # ### end Alembic commands ###
