"""19_Draft add skpt and planing id

Revision ID: e0d520c136ce
Revises: f04450ee490a
Create Date: 2023-05-04 11:06:18.383710

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'e0d520c136ce'
down_revision = 'f04450ee490a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft', sa.Column('planing_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'draft', 'planing', ['planing_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'draft', type_='foreignkey')
    op.drop_column('draft', 'planing_id')
    # ### end Alembic commands ###
