"""status bidang

Revision ID: e19fb21e1568
Revises: 751315af47e4
Create Date: 2023-08-23 10:53:54.846029

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'e19fb21e1568'
down_revision = '751315af47e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bidang_overlap', sa.Column('status_luas', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('hasil_peta_lokasi_detail', sa.Column('status_luas', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order_gambar_ukur', sa.Column('status_bidang', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_gambar_ukur', 'status_bidang')
    op.drop_column('hasil_peta_lokasi_detail', 'status_luas')
    op.drop_column('bidang_overlap', 'status_luas')
    # ### end Alembic commands ###
