"""27 Update Master Dokumen

Revision ID: e3312e901794
Revises: aeba613182f4
Create Date: 2023-06-06 16:19:17.691306

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'e3312e901794'
down_revision = 'aeba613182f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dokumen', sa.Column('key_field', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dokumen', 'key_field')
    # ### end Alembic commands ###
