"""hasil petlok dan draft detail

Revision ID: e46c87fd67ae
Revises: 227003c978aa
Create Date: 2023-08-11 10:22:43.649835

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'e46c87fd67ae'
down_revision = '227003c978aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_detail',
    sa.Column('geom', geoalchemy2.types.Geometry(from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('bidang_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('draft_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_draft_detail_geom', 'draft_detail', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_draft_detail_id'), 'draft_detail', ['id'], unique=False)
    op.create_table('hasil_peta_lokasi',
    sa.Column('bidang_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('kjb_dt_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('planing_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('ptsk_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('skpt_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('no_peta', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pemilik_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('jenis_alashak', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alashak', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('luas_surat', sa.Numeric(), nullable=False),
    sa.Column('luas_ukur', sa.Numeric(), nullable=False),
    sa.Column('luas_gu_perorangan', sa.Numeric(), nullable=True),
    sa.Column('luas_gu_pt', sa.Numeric(), nullable=True),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['bidang_id'], ['bidang.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['kjb_dt_id'], ['kjb_dt.id'], ),
    sa.ForeignKeyConstraint(['pemilik_id'], ['pemilik.id'], ),
    sa.ForeignKeyConstraint(['planing_id'], ['planing.id'], ),
    sa.ForeignKeyConstraint(['ptsk_id'], ['ptsk.id'], ),
    sa.ForeignKeyConstraint(['skpt_id'], ['skpt.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hasil_peta_lokasi_id'), 'hasil_peta_lokasi', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hasil_peta_lokasi_id'), table_name='hasil_peta_lokasi')
    op.drop_table('hasil_peta_lokasi')
    op.drop_index(op.f('ix_draft_detail_id'), table_name='draft_detail')
    op.drop_index('idx_draft_detail_geom', table_name='draft_detail', postgresql_using='gist')
    op.drop_table('draft_detail')
    # ### end Alembic commands ###
