"""tanggal transaksi

Revision ID: e50ae0056cec
Revises: 0d2f37343181
Create Date: 2023-09-25 10:38:23.557793

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e50ae0056cec'
down_revision = '0d2f37343181'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('giro_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['giro_id'], ['giro.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_id'), 'payment', ['id'], unique=False)
    op.alter_column('invoice_detail', 'invoice_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('invoice_detail', 'bidang_komponen_biaya_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.add_column('termin', sa.Column('rencana_transaksi', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('termin', 'rencana_transaksi')
    op.alter_column('invoice_detail', 'bidang_komponen_biaya_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('invoice_detail', 'invoice_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_payment_id'), table_name='payment')
    op.drop_table('payment')
    # ### end Alembic commands ###
