"""6_delete rincik_id columns in bidang overlap table

Revision ID: e5a239f73392
Revises: 7c531b434832
Create Date: 2023-04-17 16:03:58.881644

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5a239f73392'
down_revision = '7c531b434832'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bidangoverlap_rincik_id_fkey', 'bidangoverlap', type_='foreignkey')
    op.drop_column('bidangoverlap', 'rincik_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bidangoverlap', sa.Column('rincik_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('bidangoverlap_rincik_id_fkey', 'bidangoverlap', 'rincik', ['rincik_id'], ['id'])
    # ### end Alembic commands ###
