"""file type

Revision ID: e8551f7b8f0e
Revises: 9f4fe237ddd9
Create Date: 2023-07-24 16:56:09.830130

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'e8551f7b8f0e'
down_revision = '9f4fe237ddd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bundle_dt', sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bundle_dt', 'file_type')
    # ### end Alembic commands ###
