"""34 tanggal_kjb

Revision ID: e9a7abf10309
Revises: 2ea11c244084
Create Date: 2023-06-19 10:48:12.420075

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'e9a7abf10309'
down_revision = '2ea11c244084'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kjb_hd', sa.Column('tanggal_kjb', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kjb_hd', 'tanggal_kjb')
    # ### end Alembic commands ###
