"""pemilik

Revision ID: ec185d06e6c0
Revises: 
Create Date: 2023-07-27 14:10:45.373268

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'ec185d06e6c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pemilik', sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('pemilik', sa.Column('nik', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('pemilik', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pemilik', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('pemilik', 'nik')
    op.drop_column('pemilik', 'code')
    # ### end Alembic commands ###
