"""17_Update Code Counter with Id

Revision ID: ed0c0d4cbdd7
Revises: f32193b6311c
Create Date: 2023-05-03 17:53:16.066769

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'ed0c0d4cbdd7'
down_revision = 'f32193b6311c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_counter',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_counter_id'), 'code_counter', ['id'], unique=False)
    op.add_column('draft', sa.Column('skpt_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'draft', 'skpt', ['skpt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'draft', type_='foreignkey')
    op.drop_column('draft', 'skpt_id')
    op.drop_index(op.f('ix_code_counter_id'), table_name='code_counter')
    op.drop_table('code_counter')
    # ### end Alembic commands ###
