"""_m_0051

Revision ID: efd562e1ce39
Revises: 4b1a298f697d
Create Date: 2023-12-27 20:18:29.370491

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'efd562e1ce39'
down_revision = '4b1a298f697d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kjb_dt', sa.Column('group', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tanda_terima_notaris_hd', sa.Column('group', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tanda_terima_notaris_hd', 'group')
    op.drop_column('kjb_dt', 'group')
    # ### end Alembic commands ###
