"""hasil petlok detail

Revision ID: efde07d1234b
Revises: c2850c158469
Create Date: 2023-08-14 16:13:43.401275

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'efde07d1234b'
down_revision = 'c2850c158469'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hasil_peta_lokasi_detail',
    sa.Column('tipe_overlap', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bidang_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('pemilik_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('hasil_peta_lokasi_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('luas_overlap', sa.Numeric(), nullable=True),
    sa.Column('keterangan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['bidang_id'], ['bidang.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['hasil_peta_lokasi_id'], ['hasil_peta_lokasi.id'], ),
    sa.ForeignKeyConstraint(['pemilik_id'], ['pemilik.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hasil_peta_lokasi_detail_id'), 'hasil_peta_lokasi_detail', ['id'], unique=False)
    op.create_foreign_key(None, 'draft_detail', 'bidang', ['bidang_id'], ['id'])
    op.drop_column('draft_detail', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft_detail', sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'draft_detail', type_='foreignkey')
    op.drop_index(op.f('ix_hasil_peta_lokasi_detail_id'), table_name='hasil_peta_lokasi_detail')
    op.drop_table('hasil_peta_lokasi_detail')
    # ### end Alembic commands ###
