"""checklist kelengkapan dokumen

Revision ID: efe6cba1dd97
Revises: f143769a5653
Create Date: 2023-08-18 15:08:44.223398

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'efe6cba1dd97'
down_revision = 'f143769a5653'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_kelengkapan_dokumen_hd',
    sa.Column('bidang_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['bidang_id'], ['bidang.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_kelengkapan_dokumen_hd_id'), 'checklist_kelengkapan_dokumen_hd', ['id'], unique=False)
    op.create_table('checklist_kelengkapan_dokumen_dt',
    sa.Column('checklist_kelengkapan_dokumen_hd_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('jenis_bayar', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dokumen_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_kelengkapan_dokumen_hd_id'], ['checklist_kelengkapan_dokumen_hd.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['dokumen_id'], ['dokumen.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_kelengkapan_dokumen_dt_id'), 'checklist_kelengkapan_dokumen_dt', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checklist_kelengkapan_dokumen_dt_id'), table_name='checklist_kelengkapan_dokumen_dt')
    op.drop_table('checklist_kelengkapan_dokumen_dt')
    op.drop_index(op.f('ix_checklist_kelengkapan_dokumen_hd_id'), table_name='checklist_kelengkapan_dokumen_hd')
    op.drop_table('checklist_kelengkapan_dokumen_hd')
    # ### end Alembic commands ###
