"""18_Update Code Counter

Revision ID: f04450ee490a
Revises: ed0c0d4cbdd7
Create Date: 2023-05-03 18:05:24.462425

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'f04450ee490a'
down_revision = 'ed0c0d4cbdd7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_counter', sa.Column('entity', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('code_counter', sa.Column('last', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_counter', 'last')
    op.drop_column('code_counter', 'entity')
    # ### end Alembic commands ###
