"""_m_0024

Revision ID: f15139c2828b
Revises: b9ce5bac8ccc
Create Date: 2023-11-24 11:39:43.828368

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'f15139c2828b'
down_revision = 'b9ce5bac8ccc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beban_biaya', sa.Column('is_add_pay', sa.Boolean(), nullable=True))
    op.add_column('beban_biaya', sa.Column('is_retur', sa.Boolean(), nullable=True))
    op.add_column('bidang_komponen_biaya', sa.Column('is_add_pay', sa.Boolean(), nullable=True))
    op.add_column('bidang_komponen_biaya', sa.Column('is_retur', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bidang_komponen_biaya', 'is_retur')
    op.drop_column('bidang_komponen_biaya', 'is_add_pay')
    op.drop_column('beban_biaya', 'is_retur')
    op.drop_column('beban_biaya', 'is_add_pay')
    # ### end Alembic commands ###
