"""hasil petlok

Revision ID: f1532bdbdd39
Revises: 39f45a1718aa
Create Date: 2023-08-11 11:05:39.445791

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'f1532bdbdd39'
down_revision = '39f45a1718aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
