"""15_Create Code Counter Table

Revision ID: f32193b6311c
Revises: 60d6972c7370
Create Date: 2023-05-03 15:51:47.026188

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'f32193b6311c'
down_revision = '60d6972c7370'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
