"""_m_0069

Revision ID: f39cd67cda72
Revises: 9ea151fd8c0b
Create Date: 2024-02-01 15:33:55.181427

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'f39cd67cda72'
down_revision = '9ea151fd8c0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giro', sa.Column('tanggal_buka', sa.Date(), nullable=True))
    op.add_column('giro', sa.Column('tanggal_cair', sa.Date(), nullable=True))
    op.drop_column('payment', 'tanggal_cair')
    op.drop_column('payment', 'tanggal_buka')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('tanggal_buka', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('payment', sa.Column('tanggal_cair', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('giro', 'tanggal_cair')
    op.drop_column('giro', 'tanggal_buka')
    # ### end Alembic commands ###
