"""_m_0017

Revision ID: fb6c183f8e97
Revises: 53f4f61a6f37
Create Date: 2023-11-01 18:24:20.629930

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'fb6c183f8e97'
down_revision = '53f4f61a6f37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_detail', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_detail', sa.Column('amount', sa.NUMERIC(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
