"""3_recreate tanda terima notaris hd

Revision ID: fcc991ca40ec
Revises: 3a9b02a567cb
Create Date: 2023-07-06 16:39:11.104293

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fcc991ca40ec'
down_revision = '3a9b02a567cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tanda_terima_notaris_hd', 'planing_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_constraint('tanda_terima_notaris_hd_jenis_surat_id_fkey', 'tanda_terima_notaris_hd', type_='foreignkey')
    op.drop_column('tanda_terima_notaris_hd', 'kategori_penjual')
    op.drop_column('tanda_terima_notaris_hd', 'status_valid')
    op.drop_column('tanda_terima_notaris_hd', 'jenis_surat_id')
    op.drop_column('tanda_terima_notaris_hd', 'jenis_alashak')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tanda_terima_notaris_hd', sa.Column('jenis_alashak', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tanda_terima_notaris_hd', sa.Column('jenis_surat_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.add_column('tanda_terima_notaris_hd', sa.Column('status_valid', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tanda_terima_notaris_hd', sa.Column('kategori_penjual', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('tanda_terima_notaris_hd_jenis_surat_id_fkey', 'tanda_terima_notaris_hd', 'jenis_surat', ['jenis_surat_id'], ['id'])
    op.alter_column('tanda_terima_notaris_hd', 'planing_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
